Ospray3rd party
NCAR/VAPOR pull request #2417
Opened 2020-11-03 21:59 UTC by sgpearse

This PR points site.NCAR at Ospray library targets.

CircleCI is up to date with Ospray, and this should allow ospray2-gui2 to pass Circle's tests.

2020-11-03 22:02 UTC, StasJ requested changes
Can we make the ospray dir just “ospray” or “ospray2” so we don’t have to update the site file for every version change?

2020-11-03 22:35 UTC, sgpearse commented
We can.  It will take some more work, but I understand that we need to update this thing.

2020-11-04 17:20 UTC, StasJ approved these changes

2020-11-04 18:04 UTC, shaomeng commented
It looks like the same line is inserted to all 3 different conditions. Why don't have a single line that's out of the `if` block, so it's set for conditions?

2020-11-04 18:12 UTC, merged