Set cursor position to better position in VStringLineEdit
NCAR/VAPOR pull request #2564
Opened 2020-12-10 20:25 UTC by sgpearse

This change resets the VStringLineEdit's cursor to position 0 after a change is applied.  This results in more significant digits being displayed, before following digits of lesser magnitude.

2020-12-10 20:30 UTC, shaomeng approved these changes
This PR fixes the described issue on Ubuntu Linux. Could be a good idea to test on more platforms.

2020-12-10 21:24 UTC, StasJ requested changes
`VStringLineEdit::_setValueString` and `VStringLineEdit::SetValueString` are duplicates of each other and with this change will exhibit different behavior depending on which is called.

2020-12-10 21:58 UTC, sgpearse commented
You are correct.  

The duplicate private function has been removed.  This also implies un-deleting the SetValueString() function in VNumericLineEdit.

2020-12-11 08:01 UTC, StasJ approved these changes

2020-12-11 13:57 UTC, merged