Fixed #2840 - Show the number of cores OpenMP has available to it
NCAR/VAPOR pull request #3080
Opened 2022-03-29 02:43 UTC by clyne

Fixed #2840

The number of cores available to OpenMP (as returned by omp_get_num_threads()) is now displayed under Vapor/About-Vapor. Maybe there is a better place for this?

2022-03-29 02:56 UTC, shaomeng requested changes

2022-03-29 02:56 UTC, shaomeng commented on apps/vaporgui/MainForm.cpp
> +    }
If there are more than 1 thread available, the variable `nthreads` will be written simultaneously by all threads, causing a data race condition. This variable should only be written to by the 1st thread.

2022-03-29 05:49 UTC, StasJ reviewed
Maybe this could be shown in the preferences panel next to the N Threads setting?

2022-03-30 02:11 UTC, clyne commented
> Maybe this could be shown in the preferences panel next to the N Threads setting?

Agreed. I moved it.

2022-03-30 02:33 UTC, shaomeng approved these changes

2022-03-30 16:44 UTC, StasJ approved these changes

2022-03-30 16:57 UTC, merged