Build python api from source documentation
NCAR/VAPOR pull request #3262
Opened 2022-10-19 21:07 UTC by sgpearse

Fix #3196 by adding instructions to build the Python API conda tar.bz2 package from source.

2022-10-31 17:48 UTC, sgpearse commented
@NihanthCW This happens when you have a CMakeLists.txt file from a previous GUI build.  Removing the contents of your VAPOR/build directory should fix it.

2022-10-31 20:37 UTC, NihanthCW requested changes
Looks good! Thanks Scott.

2022-10-31 20:37 UTC, NihanthCW commented on docs/contributing.rst
> +    mv ~/tmp/miniconda/envs/xarray/conda-bld/linux-64/vapor-3.6.0-ha5a8b8e_0.tar.bz2 ~/channel/linux-64
swap the order of osx and linux commands to be consistent with step-1 above

2022-10-31 20:37 UTC, NihanthCW commented on docs/contributing.rst
> +5) Alternatively, add cmake build flags to your conda build such as the following:
Can we combine this with above since they are the same step?

2022-10-31 20:52 UTC, NihanthCW commented
The installation was successful. However, I am not able to import vapor. I know we ran into this issue and there was some workaround...
`ModuleNotFoundError: No module named 'vapor'`

2022-11-01 17:32 UTC, sgpearse commented
@sgpearse will re-test the build sequence and try to reproduce "No module named vapor" error.

2022-11-07 23:10 UTC, sgpearse commented
Unfortunately I'm unable to build a conda .tar.bz2 package as well, on my development macbook.  I am encountering different error than Nihanth's.  My build fails in libvdc.

CircleCI builds are currently succeeding on OSX, but I'm unclear on how their systems differ from my own.

The instructions are working for me when building on CentOS, for what it's worth.

```
[ 54%] Linking CXX shared library ../libvdc.dylib
ld: warning: directory not found for option '-L/lib-dynload'
ld: warning: -pie being ignored. It is only used when linking a main executable
ld: warning: dylib (/usr/local/lib/libudunits2.dylib) was built for newer macOS version (10.15) than being linked (10.9)
ld: warning: dylib (/usr/local/lib/libproj.dylib) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: dylib (/usr/local/lib/libhdf5.dylib) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: dylib (/usr/local/lib/libnetcdf.dylib) was built for newer macOS version (11.0) than being linked (10.9)
Undefined symbols for architecture x86_64:
  "_pj_free", referenced from:
      VAPoR::Proj4API::~Proj4API() in Proj4API.cpp.o
      VAPoR::Proj4API::~Proj4API() in Proj4API.cpp.o
      VAPoR::Proj4API::Initialize(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in Proj4API.cpp.o
  "_pj_get_def", referenced from:
      VAPoR::Proj4API::GetSrcStr() const in Proj4API.cpp.o
      VAPoR::Proj4API::GetDstStr() const in Proj4API.cpp.o
      VAPoR::Proj4API::Clamp(double*, double*, unsigned long, int) const in Proj4API.cpp.o
      VAPoR::Proj4API::IsCylindrical() const in Proj4API.cpp.o
  "_pj_get_errno_ref", referenced from:
      VAPoR::Proj4API::_Initialize(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void**, void**) const in Proj4API.cpp.o
      VAPoR::Proj4API::ProjErr() const in Proj4API.cpp.o
      VAPoR::Proj4API::_Transform(void*, void*, double*, double*, double*, unsigned long, int) const in Proj4API.cpp.o
  "_pj_init_plus", referenced from:
      VAPoR::Proj4API::_Initialize(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void**, void**) const in Proj4API.cpp.o
  "_pj_is_geocent", referenced from:
      VAPoR::Proj4API::IsGeocentSrc() const in Proj4API.cpp.o
      VAPoR::Proj4API::IsGeocentDst() const in Proj4API.cpp.o
  "_pj_is_latlong", referenced from:
      VAPoR::Proj4API::IsLatLonSrc() const in Proj4API.cpp.o
      VAPoR::Proj4API::IsLatLonDst() const in Proj4API.cpp.o
      VAPoR::Proj4API::_Transform(void*, void*, double*, double*, double*, unsigned long, int) const in Proj4API.cpp.o
      VAPoR::Proj4API::Clamp(double*, double*, unsigned long, int) const in Proj4API.cpp.o
  "_pj_latlong_from_proj", referenced from:
      VAPoR::Proj4API::_Initialize(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void**, void**) const in Proj4API.cpp.o
  "_pj_strerrno", referenced from:
      VAPoR::Proj4API::_Initialize(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void**, void**) const in Proj4API.cpp.o
      VAPoR::Proj4API::ProjErr() const in Proj4API.cpp.o
      VAPoR::Proj4API::_Transform(void*, void*, double*, double*, double*, unsigned long, int) const in Proj4API.cpp.o
  "_pj_transform", referenced from:
      VAPoR::Proj4API::_Transform(void*, void*, double*, double*, double*, unsigned long, int) const in Proj4API.cpp.o
ld: symbol(s) not found for architecture x86_64
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/vdc/CMakeFiles/vdc.dir/build.make:791: lib/libvdc.dylib] Error 1
make[1]: *** [CMakeFiles/Makefile2:441: lib/vdc/CMakeFiles/vdc.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
Traceback (most recent call last):
  File "/Users/pearse/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/pearse/miniconda3/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 496, in main
    execute(sys.argv[1:])
  File "/Users/pearse/miniconda3/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 485, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/Users/pearse/miniconda3/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/Users/pearse/miniconda3/lib/python3.9/site-packages/conda_build/build.py", line 3091, in build_tree
    packages_from_this = build(metadata, stats,
  File "/Users/pearse/miniconda3/lib/python3.9/site-packages/conda_build/build.py", line 2214, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/Users/pearse/miniconda3/lib/python3.9/site-packages/conda_build/utils.py", line 412, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/pearse/miniconda3/lib/python3.9/site-packages/conda_build/utils.py", line 392, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/Users/pearse/miniconda3/conda-bld/vapor_1667861757504/work/conda_build.sh']' returned non-zero exit status 2.
```

2022-11-08 18:22 UTC, sgpearse commented
The two problems we are facing are on Nihanth and Scott's OSX laptops.  The following platforms can successfully build and install:
1) CircleCI with an OSX executor
2) CentOS/Casper
3) CentOS and Ubuntu towers
4) Stas' personal laptop

2022-11-11 18:16 UTC, MattRehme commented
I was able to build this successfully and import it. @NihanthCW, the ModuleNotFoundError is probably due to the path to site-packages not being set, assuming it build correctly. If you haven't already, you could try:

```
>>> import sys
>>> sys.path
# ^^ To check if '~/opt/miniconda3/envs/vapor/lib/python3.9/site-packages' is in the path
# If not:
>>> sys.path.append('~/opt/miniconda3/envs/vapor/lib/python3.9/site-packages')
# Then see if vapor will import
```

I usually don't "activate" Conda environments (as in step 4), but instead run them from the absolute path. So I did the following at step 5:

```
$ conda install -n vapor -c file://"~/channel/" vapor
$ ~/opt/miniconda3/envs/vapor/bin/python3.9 -I # To start interactive session
>>> import vapor                                                                
>>> vapor                                                                       
<module 'vapor' from '~/opt/miniconda3/envs/vapor/lib/python3.9/site-packages/vapor/__init__.py'>
```

2022-11-11 18:55 UTC, NihanthCW commented
> I was able to build this successfully and import it. @NihanthCW, the ModuleNotFoundError is probably due to the path to site-packages not being set, assuming it built correctly. If you haven't already, you could try:
> 
> ```
> >>> import sys
> >>> sys.path
> # ^^ To check if '~/opt/miniconda3/envs/vapor/lib/python3.9/site-packages' is in the path
> # If not:
> >>> sys.path.append('~/opt/miniconda3/envs/vapor/lib/python3.9/site-packages')
> # Then see if vapor will import
> ```
> 
> I usually don't "activate" Conda environments (as in step 4), but instead run them from the absolute path. So I did the following at step 5:
> 
> ```
> $ conda install -n vapor -c file://"~/channel/" vapor
> $ ~/opt/miniconda3/envs/vapor/bin/python3.9 -I # To start interactive session
> >>> import vapor                                                                
> >>> vapor                                                                       
> <module 'vapor' from '~/opt/miniconda3/envs/vapor/lib/python3.9/site-packages/vapor/__init__.py'>
> ```

Perfect! Thanks @MattRehme . This worked. Interestingly my path is slightly different. I donot have the _opt_ folder. What determines this path? i.e., is this determined when miniconda is installed? 

Regarding the environments: I think using environments ensures that we don't mess up dependencies and use the correct versions between projects, right? I know you work with python regularly, so curious to know if you manage this is some other way.

2022-11-11 19:03 UTC, MattRehme commented
> Perfect! Thanks @MattRehme . This worked. Interestingly my path is slightly different. I donot have the _opt_ folder. What determines this path? i.e., is this determined when miniconda is installed?
> 
> Regarding the environments: I think using environments ensures that we don't mess up dependencies and use the correct versions between projects, right? I know you work with python regularly, so curious to know if you manage this is some other way.

@NihanthCW, correct, the envs allow you to use different versions of packages per project. I'm still using an environment, I just don't run the activate or init commands because it creates a second shell and sometimes modifies your .bashrc/.bash_profile. Instead, I run Python via an absolute path, which still imports the correct sys.path specific to that environment.

As for the opt, correct, it's determined in the Miniconda3 install. I have tried to change this in my install, but it doesn't seem to work. I may be doing something wrong.

2022-11-11 19:10 UTC, MattRehme approved these changes
Changes look good. I was able to build via this documentation and run 'import vapor' in Python (see discussion for more info).

2022-11-11 19:12 UTC, NihanthCW approved these changes
Looks good to me

2022-11-11 19:22 UTC, NihanthCW commented
> > Perfect! Thanks @MattRehme . This worked. Interestingly my path is slightly different. I donot have the _opt_ folder. What determines this path? i.e., is this determined when miniconda is installed?
> > Regarding the environments: I think using environments ensures that we don't mess up dependencies and use the correct versions between projects, right? I know you work with python regularly, so curious to know if you manage this is some other way.
> 
> @NihanthCW, correct, the envs allow you to use different versions of packages per project. I'm still using an environment, I just don't run the activate or init commands because it creates a second shell and sometimes modifies your .bashrc/.bash_profile. Instead, I run Python via an absolute path, which still imports the correct sys.path specific to that environment.
> 
> As for the opt, correct, it's determined in the Miniconda3 install. I have tried to change this in my install, but it doesn't seem to work. I may be doing something wrong.

Hmm... You should show me how you do this in our next meeting. I'm learning :-)

@sgpearse At this stage if this looks good to @StasJ , we should merge this sooner than later for folks who might try this after Stas's talk at the ESDS meeting. 
Scott, I know there might be some issue with Macs as per your previous comment. Since we are having trouble reproducing it, what do think about merging it and reopening the issue if any of our users encounter the same?

2022-11-11 19:56 UTC, sgpearse commented
> @sgpearse At this stage if this looks good to @StasJ , we should merge this sooner than later for folks who might try this after Stas's talk at the ESDS meeting.
> Scott, I know there might be some issue with Macs as per your previous comment. Since we are having trouble reproducing it, what do think about merging it and reopening the issue if any of our users encounter the same?

Sounds good to me.

2022-11-14 19:53 UTC, StasJ reviewed
Looks good to me. My only suggestion is to use `$CONDA_PREFIX` to point to the environment root so where you use `~/tmp/miniconda/envs/xarray/conda-bld/osx-64/vapor-3.6.0-ha5a8b8e_0.tar.bz2` you could replace it with `$CONDA_PREFIX/conda-bld/osx-64/vapor-3.6.0-ha5a8b8e_0.tar.bz2`

2022-11-18 15:39 UTC, merged