Python API documentation overhaul
NCAR/VAPOR pull request #3315
Opened 2023-01-20 19:58 UTC by sgpearse

Fixes #3304, #3295, #3290, and #3119

This PR makes the following changes to our documentation

1) Switch themes from sphinx-rtd-theme to sphinx-book-theme
2) Adds Python API installation instructions, examples, and class reference
3) Moves documentation content into three primary sections, 1) Data formatting requirements, 2) Vapor application reference, and 3) Python API reference
4) Many organizational changes and naming changes
5) readTheDocs is now configured to build using a conda environment

The large number of files changed (447) are due to 1) the Python API having many classes that are documented in this PR, and 2) Renaming directories changes all contained files.

I suggest comparing the current docs with the ones in this PR via the following links:
[Current website](https://vapor.readthedocs.io/en/readthedocs/#)
[New website in this PR](https://vapor.readthedocs.io/en/pythonhelp/index.html)

2023-01-23 20:15 UTC, NihanthCW approved these changes
This looks good to me.
The actual python api reference can be polished in appearance but as we've discussed earlier, we can address that is successive iterations. I think this is a very good starting point. Thanks Scott!

2023-01-23 21:19 UTC, StasJ requested changes
## Requested Changes

I believe it is standard practice not to include generated files in git repos since a small change in one of the config files may result in a commit with tens of thousands of changes. 

We probably don't need to expose internal python modules like `vapor.cppyyDoxygenWrapper` or `vapor.renderer.FuncWrapperRegex` since those are not relevant to the end user. In some cases they are the majority which could make it hard to navigate. For example, below there is only one relevant module:

<img width="300" alt="s1" src="https://user-images.githubusercontent.com/2772687/214151212-45567460-67fa-4a95-b08e-1491956c0ff5.png">

## Comments

Would it be possible to include some sort of formatting to make it more readable? For example in [xarray's documentation](https://docs.xarray.dev/en/stable/generated/xarray.plot.FacetGrid.html) the formatting makes it easier to distinguish different elements while in Vapor's doc everything except the class name is plain text.

2023-01-31 22:01 UTC, StasJ approved these changes

2023-02-02 19:14 UTC, NihanthCW approved these changes

2023-02-02 21:13 UTC, shaomeng approved these changes

2023-02-07 18:16 UTC, merged