Change notifier URL to one with an improved repository name
NCAR/VAPOR pull request #3336
Opened 2023-02-22 16:39 UTC by sgpearse

The repository that hosts Vapor's landing page at https://www.vapor.ucar.edu/ is named `Vapor-SupportPage `because it was previously used as a user support form years ago.  Since it is no longer used for that, it would be less confusing if it had a more descriptive name.

We also use this repository to store Vapor's notifications.  This PR updates the URL used by the notifier to direct to a repository named `VAPOR-LandingPage`, instead of `VAPOR-SupportPage`.

Once this is merged, we can change the actual repository name without breaking the notifier.

2023-02-22 17:14 UTC, NihanthCW approved these changes
Looks good. I guess you were anyway planning to do this but I would just double check after this is merged to ensure everything is working.

2023-02-22 17:47 UTC, StasJ requested changes
This will break the notifier for all current and previous versions of Vapor.

2023-02-22 17:55 UTC, sgpearse commented
@stasj - Do you think there is an ideal time to do this, or that it should not be done at all?  Some things to consider are 1) whether we plan on having any notifications before 3.8.1's release, and 2) Vapor's release notification system does not use this repository, and would be unaffected by this.

The last time we changed the VAPOR-SupportPage repo's name, it did indeed break the notifier.  Conversely, it seems that [github should be redirecting references](https://github.com/orgs/community/discussions/22669#discussioncomment-3237667) to the old repo to the new one.  I don't know why that didn't happen last time.

2023-02-22 22:36 UTC, StasJ commented
@sgpearse I believe last time it was changed by accident. Let's discuss in person tomorrow.

2023-02-23 19:32 UTC, sgpearse commented
Per today's discussion, we will opt not to change the repo's name and live with this quirk so that we don't break the notifier in previous Vapor versions.

2023-02-23 19:32 UTC, closed without merging