Fix #3440: Moving domain bug
NCAR/VAPOR pull request #3445
Opened 2023-08-24 16:14 UTC by StasJ

Fix #3440

2023-08-29 23:12 UTC, sgpearse requested changes
Follow the steps in the bug report, then disable the Volume and Image renderers.  The Flow region is incorrect.

![Screen Shot 2023-08-29 at 5 12 06 PM](https://github.com/NCAR/VAPOR/assets/9522770/aa05ddd4-17e4-4f83-9fb0-6e3676a02326)

2023-09-01 13:49 UTC, StasJ commented
> Follow the steps in the bug report, then disable the Volume and Image renderers. The Flow region is incorrect.

I get correct results when following your directions:

<img width="1141" alt="ss" src="https://github.com/NCAR/VAPOR/assets/2772687/86636e5c-fd5e-403c-bf1a-310ca4ba017a">

2023-09-01 14:19 UTC, sgpearse commented
That's really strange.  When I load domain.vs3 in the zip file from the bug report, and disable all renderers but flow, something goes awry.  I'm definitely on issue3340.

![Screen Shot 2023-09-01 at 8 18 04 AM](https://github.com/NCAR/VAPOR/assets/9522770/ecabb5eb-c120-49dd-ad34-8f1631d116ae)

2023-09-01 14:28 UTC, StasJ commented
> That's really strange. When I load domain.vs3 in the zip file from the bug report, and disable all renderers but flow, something goes awry. I'm definitely on issue3340.

1. Loading `domain.vs3` is not one of the steps in the bug report:
> Follow the steps in the bug report, then disable...

2. That session file was generated using a bug. The bug was fixed, but it does not retroactively repair bad session files, especially since we never released a version containing this bug.

2023-09-01 23:04 UTC, StasJ commented
> That's fair, however when not using the session file I see the following which is the incorrect behavior from my screenshot 3 days ago :(. The domain is too long on the Y axis and the northern region of the flow renderer is truncated.
> 
> I'm not sure how we're seeing two different things. Would it be useful to do a screen share?

Just a sanity check: Are you using the pre-release installer or building from this branch for your tests?

2023-09-01 23:07 UTC, sgpearse commented
> Just a sanity check: Are you using the pre-release installer or building from this branch for your tests?

I'm building on issue3440 in debug mode with all other defaults applied.  But I don't think there's urgency since we've agreed to postpone this edge case until after release.  I'd like to do a screen-share when we meet on Tuesday though, just for sanity.

2023-09-18 17:18 UTC, sgpearse approved these changes

2023-09-18 17:18 UTC, merged